import {
  brand1,
  brand2,
  brand3,
  brand4,
  brand5,
  brand6,
  brand7,
  brand8,
  brand9,
  brand10,
  brand11,
  brand12,
  brand13,
  brand14,
  brand15,
  brand16,
  brand17,
  brand18,
} from "@/common";

export const BRANDS = [
  { name: "Ferrari", logo: brand1 },
  { name: "Lamborghini", logo: brand2 },
  { name: "McLaren", logo: brand3 },
  { name: "Porsche", logo: brand4 },
  { name: "Bentley", logo: brand5 },
  { name: "Rolls-Royce", logo: brand6 },
  { name: "Aston Martin", logo: brand7 },
  { name: "Bugatti", logo: brand8 },
  { name: "Maserati", logo: brand9 },
  { name: "Mercedes-AMG", logo: brand10 },
  { name: "BMW M", logo: brand11 },
  { name: "Audi R", logo: brand12 },
  { name: "Koenigsegg", logo: brand13 },
  { name: "Pagani", logo: brand14 },
  { name: "Lotus", logo: brand15 },
  { name: "Alfa Romeo", logo: brand16 },
  { name: "Jaguar", logo: brand17 },
  { name: "Lexus F", logo: brand18 },
];

